"use client";

import React from "react";
import { Handle, Position } from "@xyflow/react";
import { 
  FileCheck, 
  ExternalLink,
  MoreVertical,
  Download,
  Share2
} from "lucide-react";
import { cn } from "@/lib/utils";
import { motion } from "framer-motion";
import Link from "next/link";

export function ResultNode({ data }: { data: any }) {
  return (
    <motion.div
      initial={{ scale: 0.9, opacity: 0 }}
      animate={{ scale: 1, opacity: 1 }}
      whileHover={{ scale: 1.02, y: -5 }}
      className={cn(
        "group relative min-w-[280px] glass p-8 rounded-[2.5rem] border-2 border-honey-500 bg-honey-50/10 shadow-2xl shadow-honey-500/10 transition-all duration-500 cursor-grab active:cursor-grabbing"
      )}
    >
      <div className="absolute inset-0 rounded-[2.5rem] overflow-hidden pointer-events-none">
        {/* Background Pattern */}
        <div className="absolute top-0 right-0 p-4 opacity-5 pointer-events-none">
          <FileCheck size={120} className="rotate-12" />
        </div>
        {/* Gloss Effect */}
        <div className="absolute inset-0 bg-gradient-to-tr from-transparent via-white/5 to-white/10 pointer-events-none" />
      </div>

      {/* Connector Handles */}
      <Handle 
        type="target" 
        position={Position.Left} 
        className="!w-4 !h-4 !bg-honey-500 !border-4 !border-white !shadow-lg hover:!scale-125 transition-transform" 
      />

      <div className="flex flex-col gap-6 relative z-10">
        <div className="flex items-start justify-between">
          <div className="w-14 h-14 rounded-2xl bg-honey-500 flex items-center justify-center text-white shadow-lg shadow-honey-500/40">
            <FileCheck className="w-7 h-7" />
          </div>
          <div className="flex gap-1">
            <button className="p-2 hover:bg-honey-100 rounded-lg transition-colors opacity-40 hover:opacity-100">
              <Share2 size={16} />
            </button>
            <button className="p-2 hover:bg-honey-100 rounded-lg transition-colors opacity-40 hover:opacity-100">
              <MoreVertical size={16} />
            </button>
          </div>
        </div>
        
        <div className="space-y-1 text-left">
          <p className="text-[10px] font-bold uppercase tracking-[0.3em] text-honey-600">Artifact Ready</p>
          <h3 className="text-xl font-display font-bold uppercase tracking-tight leading-tight">{data.label}</h3>
        </div>

        <div className="flex flex-col gap-3">
          <Link 
            href={`/artifacts/${data.artifactId || 'preview'}`}
            className="w-full flex items-center justify-center gap-3 bg-bee-black text-white px-6 py-4 rounded-2xl hover:bg-honey-600 transition-all text-xs font-bold uppercase tracking-widest shadow-xl group/btn"
          >
            <span>View Full Result</span>
            <ExternalLink size={14} className="group-hover/btn:translate-x-1 group-hover/btn:-translate-y-1 transition-transform" />
          </Link>
          
          <button className="w-full flex items-center justify-center gap-3 border border-border/40 px-6 py-4 rounded-2xl hover:bg-honey-50 transition-all text-[10px] font-bold uppercase tracking-widest opacity-60 hover:opacity-100">
            <Download size={14} />
            Download Source
          </button>
        </div>

        <div className="flex items-center gap-4 pt-2">
          <div className="flex -space-x-2">
            {[1, 2, 3].map((i) => (
              <div key={i} className="w-6 h-6 rounded-full border-2 border-white bg-honey-200 flex items-center justify-center text-[8px] font-bold">
                {String.fromCharCode(64 + i)}
              </div>
            ))}
          </div>
          <span className="text-[10px] font-medium opacity-40">Generated by 3 Agents</span>
        </div>
      </div>

      {/* Gloss Effect */}
      <div className="absolute inset-0 bg-gradient-to-tr from-transparent via-white/5 to-white/10 pointer-events-none" />
    </motion.div>
  );
}
