"""End-to-end pipeline behaviour, run against a real database and the offline model."""

from __future__ import annotations

import asyncio
import json
import sqlite3
import threading
import uuid

import httpx
import pytest

from backend.handlers.generate_handler import GenerateHandler
from backend.handlers.ingest_handler import IngestHandler
from backend.handlers.sources import SourceResolver
from backend.llm.base import LLMError
from backend.llm.openrouter import OpenRouterProvider
from backend.llm.schema import extract_json, parse_as
from backend.models.artifacts import StudyGuideModel
from backend.models.graph import JobBundle
from backend.models.jobs import JobModel
from backend.pipeline.cleaning import TextCleaner
from backend.services.flow import FlowEngine
from backend.services.job_runner import JobExecutor, is_transient

FENCED_BODY = "Run it:\n\n```python\nprint(quorum)\n```\n\nThen read the output."

PDF_TEXT = (
    "--- Page 1 ---\n"
    "Let f(x) = 2x on the interval [0,1].\n"
    "NOTE: the ratio 3:14 is not a timestamp.\n\n"
    "--- Page 2 ---\n"
    "Sorting the list costs O(n log n) time [Knuth 1998]."
)

TRANSCRIPT_TEXT = "SPEAKER: So at 12:34 (laughs) any two [inaudible] quorums intersect."

LECTURE_SENTENCE = (
    "The pigeonhole principle forces any two majority quorums to overlap in at least one node."
)

OFFLINE_MARKER = "Generated by the BeePrepared offline provider"


def lecture_transcript(paragraphs: int = 40) -> str:
    """
    A transcript long enough to be chunked, carrying one sentence worth finding.

    The repair pass splits at four thousand characters, so the sentence is
    repeated: exactly one copy per boundary can be cut in half, and the rest
    prove whether the pass returned the lecture or something it invented.
    """
    body = (
        "Today we look at how a replicated log stays consistent when machines fail. "
        "A leader accepts every write and copies it to the followers before it acknowledges. "
    )
    return " ".join(f"{body}{LECTURE_SENTENCE}" for _ in range(paragraphs))


def queue(database, project_id: str, job_type: str, payload: dict) -> JobModel:
    """Insert a job and claim it, the way a worker would."""
    row = database.insert("jobs", {
        "project_id": project_id, "type": job_type, "status": "pending", "payload": payload,
    })[0]
    return database.claim_job(row["id"])


def run(database, project_id: str, job_type: str, payload: dict) -> tuple[bool, JobModel]:
    """Queue a job and execute it, returning whether it committed."""
    job = queue(database, project_id, job_type, payload)
    return asyncio.run(JobExecutor(database).execute(job)), job


def run_threads(target, *, count: int) -> None:
    """Run `target` on `count` real threads and wait for all of them."""
    threads = [threading.Thread(target=target) for _ in range(count)]
    for thread in threads:
        thread.start()
    for thread in threads:
        thread.join(timeout=30)
    assert not any(thread.is_alive() for thread in threads), "a thread did not finish"


def notes_then_quiz(artifact_id: str) -> tuple[list[dict], list[dict]]:
    """A canvas of one source feeding notes, whose output feeds a quiz."""
    return (
        [
            {"id": "s1", "type": "artifactNode", "data": {"artifact": {"id": artifact_id}}},
            {"id": "g1", "type": "generator", "data": {"subType": "notes"}},
            {"id": "g2", "type": "generator", "data": {"subType": "quiz"}},
        ],
        [
            {"id": "e1", "source": "s1", "target": "g1"},
            {"id": "e2", "source": "g1", "target": "g2"},
        ],
    )


def record_flow_events(monkeypatch) -> list[tuple[str, dict]]:
    """Capture what the engine tells the browser, in the order it is told."""
    from backend.services.flow import engine as flow_engine

    seen: list[tuple[str, dict]] = []
    monkeypatch.setattr(
        flow_engine,
        "publish",
        lambda project_id, event_type, data=None: seen.append((event_type, data or {})),
    )
    return seen


def study_guide_payload(body: str) -> dict:
    """A complete study guide, the live schema whose body is free-form Markdown."""
    return {
        "title": "Quorums",
        "estimated_minutes": 30,
        "objectives": ["Know why two majorities must intersect"],
        "body": body,
        "checklist": ["Can you state the intersection property?"],
    }


def exhausted_failure(monkeypatch, transport_error: Exception) -> BaseException:
    """Drive `_send` against a transport that always fails and return what it raised."""
    from backend.core.config import get_settings

    monkeypatch.setenv("OPENROUTER_API_KEY", "test-key")
    monkeypatch.setenv("LLM_MAX_RETRIES", "1")
    get_settings.cache_clear()

    async def always_fail(*args, **kwargs):
        raise transport_error

    monkeypatch.setattr(httpx.AsyncClient, "post", always_fail)

    with pytest.raises(LLMError) as raised:
        asyncio.run(OpenRouterProvider()._send({"model": "test"}))
    return raised.value


class TestResponseParsing:
    def test_a_code_fence_inside_the_document_survives(self):
        """The fence pattern used to match inside the body and return its contents."""
        payload = study_guide_payload(FENCED_BODY)

        guide = parse_as(json.dumps(payload), StudyGuideModel)

        assert guide.body == FENCED_BODY
        assert guide.title == "Quorums"

    def test_a_fenced_response_is_still_unwrapped(self):
        payload = study_guide_payload("Majorities overlap. No fence here.")
        fenced = f"```json\n{json.dumps(payload)}\n```"

        assert json.loads(extract_json(fenced)) == payload
        assert parse_as(fenced, StudyGuideModel).body == payload["body"]


class TestProviderFailureClassification:
    @pytest.mark.parametrize("transport_error", [
        httpx.ConnectTimeout(""),
        httpx.ReadTimeout(""),
        httpx.ConnectError("[Errno 61] Connection refused"),
    ])
    def test_an_exhausted_network_failure_stays_transient(self, monkeypatch, transport_error):
        """Wrapping used to discard the type, and these carry no message to match on."""
        assert is_transient(exhausted_failure(monkeypatch, transport_error))

    def test_an_exhausted_failure_names_the_fault_it_gave_up_on(self, monkeypatch):
        failure = exhausted_failure(monkeypatch, httpx.ConnectTimeout(""))

        assert "ConnectTimeout" in str(failure)

    def test_a_malformed_payload_is_still_permanent(self, monkeypatch):
        """Rescuing network faults must not make every provider failure retryable."""
        from backend.core.config import get_settings

        monkeypatch.setenv("OPENROUTER_API_KEY", "test-key")
        get_settings.cache_clear()

        async def answer_with_prose(self, body):
            return "Sure! Here is your study guide."

        monkeypatch.setattr(OpenRouterProvider, "_send", answer_with_prose)

        with pytest.raises(LLMError) as raised:
            asyncio.run(OpenRouterProvider().complete_as("go", StudyGuideModel))

        assert not is_transient(raised.value)


class RecordingCleaner:
    """Stands in for the cleaner and records which path the handler chose."""

    def __init__(self) -> None:
        self.paths: list[str] = []

    async def clean(self, text: str) -> str:
        self.paths.append("document")
        return text

    async def clean_transcript(self, text: str, *, use_model: bool = True) -> str:
        self.paths.append("transcript")
        return text


class TestCleaning:
    """
    A document is not a transcript, and used to be cleaned as though it were.

    The transcript rules delete every parenthesised and bracketed span, so a
    maths or computer-science PDF lost the notation it is made of, silently,
    before the knowledge core and every artifact under it were built on it.
    """

    def test_a_document_keeps_mathematical_and_bracketed_notation(self):
        cleaned = asyncio.run(TextCleaner().clean(PDF_TEXT))

        for notation in ("f(x) = 2x", "[0,1]", "O(n log n)", "[Knuth 1998]", "NOTE:", "3:14"):
            assert notation in cleaned, f"cleaning ate {notation}"

    def test_page_markers_survive_a_document_clean(self):
        """The reader inserts them deliberately: they are structure, not noise."""
        cleaned = asyncio.run(TextCleaner().clean(PDF_TEXT))

        assert cleaned.startswith("--- Page 1 ---\n")
        assert "\n--- Page 2 ---\n" in cleaned

    def test_a_transcript_still_loses_asides_labels_and_timestamps(self):
        cleaned = asyncio.run(TextCleaner().clean_transcript(TRANSCRIPT_TEXT, use_model=False))

        for noise in ("(laughs)", "laughs", "[inaudible]", "inaudible", "SPEAKER:", "12:34"):
            assert noise not in cleaned, f"cleaning kept {noise}"
        assert "any two quorums intersect" in cleaned

    @pytest.mark.parametrize("source_type, path", [
        ("audio", "transcript"),
        ("video", "transcript"),
        ("youtube", "transcript"),
        ("pdf", "document"),
        ("pptx", "document"),
        ("md", "document"),
    ])
    def test_only_transcribed_sources_reach_the_transcript_rules(self, source_type, path):
        """Every source type used to get them, documents included."""
        cleaner = RecordingCleaner()

        asyncio.run(IngestHandler(cleaner=cleaner)._clean(PDF_TEXT, source_type))

        assert cleaner.paths == [path]


class TestTranscriptRepairKeepsTheSource:
    """
    The cleaning pass edits the transcript; it must never author a new one.

    This is the project's worst bug and its whole class. The offline provider
    hands a prompt its own input back only when it recognises the prompt as an
    edit, the cleaning prompt says "summarise", and the recogniser only knew
    "summarize", so a whole lecture was replaced by a synthetic study document.
    Nothing raised: the knowledge core and every artifact under it were built on
    text nobody had ever said.
    """

    def test_the_repair_prompt_is_recognised_as_an_edit_by_the_offline_provider(self):
        """
        The cheap half: the prompt and the recogniser pinned to each other.

        Neither can be reworded on its own after this, which is the failure that
        has no other symptom.
        """
        from backend.llm.offline import OfflineProvider
        from backend.pipeline.cleaning import REPAIR_PROMPT

        assert OfflineProvider._wants_the_source_back(REPAIR_PROMPT) is True

    def test_a_repaired_transcript_still_contains_the_lecture(self):
        """
        The whole class: the real cleaner, the real provider, a real transcript.

        Only the output can tell the difference between a repair and a
        replacement, so this reads the output rather than the recogniser.
        """
        from backend.llm.offline import OfflineProvider

        transcript = lecture_transcript()

        cleaned = asyncio.run(TextCleaner(OfflineProvider()).clean_transcript(transcript))

        assert LECTURE_SENTENCE in cleaned
        assert OFFLINE_MARKER not in cleaned
        assert cleaned.count(LECTURE_SENTENCE) >= transcript.count(LECTURE_SENTENCE) - 3
        assert len(cleaned) > len(transcript) * 0.9

    def test_the_ingest_handler_sends_a_transcript_down_that_same_path(self):
        """The door the bug came through: ingest picks the rules, then repairs."""
        from backend.llm.offline import OfflineProvider

        handler = IngestHandler(cleaner=TextCleaner(OfflineProvider()))

        cleaned = asyncio.run(handler._clean(lecture_transcript(), "audio"))

        assert LECTURE_SENTENCE in cleaned
        assert OFFLINE_MARKER not in cleaned


class TestGeneration:
    @pytest.mark.parametrize(
        "target",
        ["quiz", "flashcards", "notes", "slides", "study_guide", "cheatsheet", "mindmap", "exam"],
    )
    def test_every_artifact_type_generates_and_commits(self, database, project, knowledge_core, target):
        committed, job = run(database, project["id"], "generate", {
            "target_type": target, "source_artifact_ids": [knowledge_core["id"]],
        })
        assert committed, f"{target} did not commit"

        artifacts = database.select(
            "artifacts", [("project_id", f"eq.{project['id']}"), ("type", f"eq.{target}")]
        )
        assert len(artifacts) == 1
        assert artifacts[0]["content"]["data"]

        finished = database.get_job(job.id)
        assert finished["status"] == "completed"
        assert finished["result"]["artifact_type"] == target

    def test_an_exam_commits_its_rendered_booklet_alongside_the_questions(
        self, database, project, knowledge_core
    ):
        """
        The exam is the only type assembled from batches and typeset by a tool.

        A failed export is logged rather than raised, so the job completing says
        nothing about whether a booklet came out; the stored export is what has
        to be looked at. Which format arrives depends on whether pdflatex is
        installed, so both of its answers are accepted.
        """
        from backend.services.exports import MIME_TYPES
        from backend.services.files import get_file_store
        from backend.services.generators import EXAM_BATCHES

        committed, _ = run(database, project["id"], "generate", {
            "target_type": "exam", "source_artifact_ids": [knowledge_core["id"]],
        })
        assert committed

        exam = database.select(
            "artifacts", [("type", "eq.exam"), ("project_id", f"eq.{project['id']}")]
        )[0]

        questions = exam["content"]["data"]["questions"]
        assert len(questions) > max(count for _, count, _ in EXAM_BATCHES), "one batch is not an exam"
        assert [question["id"] for question in questions] == [
            f"Q-{number}" for number in range(1, len(questions) + 1)
        ], "batches are renumbered once they are merged"

        export = exam["content"]["binary"]
        assert export["format"] in {"pdf", "tex"}
        assert export["mime_type"] == MIME_TYPES[export["format"]]
        assert get_file_store().size_of(export["storage_path"]) == export["size_bytes"] > 0

    def test_multi_input_records_one_edge_per_source(self, database, project, knowledge_core):
        """Provenance survives fan-in: three sources produce three edges."""
        extra = [
            database.insert("artifacts", {
                "project_id": project["id"],
                "type": "knowledge_core",
                "content": {"kind": "core", "core": {
                    **knowledge_core["content"]["core"], "title": f"Source {index}",
                }},
            })[0]
            for index in range(2)
        ]
        sources = [knowledge_core["id"]] + [artifact["id"] for artifact in extra]

        committed, _ = run(database, project["id"], "generate", {
            "target_type": "notes", "source_artifact_ids": sources,
        })
        assert committed

        notes = database.select(
            "artifacts", [("project_id", f"eq.{project['id']}"), ("type", "eq.notes")]
        )[0]
        edges = database.get_parent_edges(notes["id"])
        assert sorted(edge["parent_artifact_id"] for edge in edges) == sorted(sources)

    def test_duplicate_sources_collapse_to_one_edge(self, knowledge_core):
        handler = GenerateHandler()
        assert handler._unique([knowledge_core["id"], knowledge_core["id"]]) == [knowledge_core["id"]]

    def test_chaining_reads_the_chained_artifact_not_its_ancestor(self, database, project, knowledge_core):
        """notes into quiz must read the notes, not regenerate from the core."""
        committed, _ = run(database, project["id"], "generate", {
            "target_type": "notes", "source_artifact_ids": [knowledge_core["id"]],
        })
        assert committed

        notes = database.select(
            "artifacts", [("type", "eq.notes"), ("project_id", f"eq.{project['id']}")]
        )[0]

        cores = SourceResolver(database).resolve([notes["id"]], "quiz")
        assert len(cores) == 1
        assert notes["content"]["data"]["body"][:80] in cores[0].summary

    def test_unknown_target_type_fails_the_job(self, database, project, knowledge_core):
        committed, job = run(database, project["id"], "generate", {
            "target_type": "horoscope", "source_artifact_ids": [knowledge_core["id"]],
        })
        assert not committed
        assert database.get_job(job.id)["status"] == "failed"

    def test_missing_source_fails_with_a_clear_message(self, database, project):
        committed, job = run(database, project["id"], "generate", {
            "target_type": "quiz", "source_artifact_ids": [str(uuid.uuid4())],
        })
        assert not committed

        failed = database.get_job(job.id)
        assert failed["status"] == "failed"
        assert "not found" in failed["error_message"].lower()

    def test_generation_is_steerable(self, database, project, knowledge_core):
        committed, _ = run(database, project["id"], "generate", {
            "target_type": "quiz",
            "source_artifact_ids": [knowledge_core["id"]],
            "instructions": "focus only on quorums",
        })
        assert committed

        quiz = database.select(
            "artifacts", [("type", "eq.quiz"), ("project_id", f"eq.{project['id']}")]
        )[0]
        assert quiz["content"]["instructions"] == "focus only on quorums"


class TestRefinement:
    def test_refine_appends_a_version_linked_to_the_original(self, database, project, knowledge_core):
        run(database, project["id"], "generate", {
            "target_type": "quiz", "source_artifact_ids": [knowledge_core["id"]],
        })
        original = database.select(
            "artifacts", [("type", "eq.quiz"), ("project_id", f"eq.{project['id']}")]
        )[0]

        committed, _ = run(database, project["id"], "refine", {
            "source_artifact_id": original["id"], "instructions": "make the questions harder",
        })
        assert committed

        quizzes = database.select(
            "artifacts", [("type", "eq.quiz"), ("project_id", f"eq.{project['id']}")]
        )
        assert len(quizzes) == 2, "refinement should append, not overwrite"

        revised = next(quiz for quiz in quizzes if quiz["id"] != original["id"])
        assert revised["content"]["refined_from"] == original["id"]
        assert database.get_parent_edges(revised["id"])[0]["parent_artifact_id"] == original["id"]

    def test_refine_without_instructions_is_rejected(self, database, project):
        artifact = database.insert("artifacts", {
            "project_id": project["id"],
            "type": "quiz",
            "content": {"kind": "generated", "data": {"title": "Q", "questions": []}},
        })[0]

        committed, job = run(database, project["id"], "refine", {
            "source_artifact_id": artifact["id"], "instructions": "   ",
        })
        assert not committed
        assert "instructions is required" in database.get_job(job.id)["error_message"]


class TestRetryPolicy:
    @pytest.mark.parametrize("message", [
        "HTTP 429: rate limit exceeded",
        "Read timed out",
        "503 Service Unavailable",
        "upstream is overloaded",
    ])
    def test_transient_failures_retry(self, message):
        assert is_transient(RuntimeError(message))

    @pytest.mark.parametrize("message", [
        "target_type is required",
        "Source artifacts not found: abc",
        "Expected at least 5 questions, got 2",
    ])
    def test_permanent_failures_do_not_retry(self, message):
        assert not is_transient(ValueError(message))

    @pytest.mark.parametrize("identifier", [
        "429e4567-e89b-12d3-a456-426614174000",
        "Source artifacts not found: 502",
        "artifact 504 has no content",
    ])
    def test_status_digits_inside_identifiers_do_not_trigger_a_retry(self, identifier):
        """A bare three-digit match would retry anything containing those digits."""
        assert not is_transient(ValueError(f"Source artifacts not found: {identifier}"))

    def test_a_transient_failure_requeues_until_attempts_run_out(self, database, project, monkeypatch):
        monkeypatch.setenv("JOB_MAX_ATTEMPTS", "2")
        from backend.core.config import get_settings

        get_settings.cache_clear()

        job = queue(database, project["id"], "generate", {"target_type": "quiz"})
        assert database.fail_job(job.id, "HTTP 429: rate limit", retryable=True) == "pending"
        assert database.get_job(job.id)["status"] == "pending"

        database.claim_job(job.id)
        assert database.fail_job(job.id, "HTTP 429: rate limit", retryable=True) == "failed"


class TestQueue:
    def test_a_job_is_claimed_exactly_once(self, database, project):
        """Without an atomic claim, two workers run the same job."""
        row = database.insert("jobs", {
            "project_id": project["id"], "type": "generate", "status": "pending", "payload": {},
        })[0]

        first, second = database.claim_job(), database.claim_job()

        assert first is not None and str(first.id) == row["id"]
        assert second is None

    def test_stale_running_jobs_return_to_the_queue(self, database, project):
        """Without the reaper, a crashed worker strands its job forever."""
        row = database.insert("jobs", {
            "project_id": project["id"], "type": "generate", "status": "pending", "payload": {},
        })[0]
        database.claim_job(row["id"])
        assert database.get_job(row["id"])["status"] == "running"

        assert database.reap_stale_jobs(older_than_seconds=-1) == [row["id"]]
        assert database.get_job(row["id"])["status"] == "pending"

    def test_a_stale_job_with_no_attempts_left_is_failed_rather_than_requeued(
        self, database, project, monkeypatch
    ):
        """
        The reaper's other branch, and the one that stops the loop.

        A job that dies the same way every time would otherwise be requeued
        forever: the reaper hands it back, the next worker dies on it, and the
        node spins with no error for as long as the process lives.
        """
        from backend.core.config import get_settings

        monkeypatch.setenv("JOB_MAX_ATTEMPTS", "1")
        get_settings.cache_clear()

        row = database.insert("jobs", {
            "project_id": project["id"], "type": "generate", "status": "pending", "payload": {},
        })[0]
        database.claim_job(row["id"])

        assert database.reap_stale_jobs(older_than_seconds=-1) == [row["id"]]

        reaped = database.get_job(row["id"])
        assert reaped["status"] == "failed"
        assert "no attempts left" in reaped["error_message"]
        assert database.claim_job() is None

    def test_a_committed_job_cannot_commit_twice(self, database, project, knowledge_core):
        committed, job = run(database, project["id"], "generate", {
            "target_type": "quiz", "source_artifact_ids": [knowledge_core["id"]],
        })
        assert committed

        with pytest.raises(ValueError, match="already completed"):
            database.commit_bundle(JobBundle(job_id=job.id, project_id=project["id"]))

    def test_cancelling_takes_a_job_off_the_queue(self, database, project):
        row = database.insert("jobs", {
            "project_id": project["id"], "type": "generate", "status": "pending", "payload": {},
        })[0]

        assert database.cancel_job(row["id"]) is True
        assert database.claim_job() is None
        assert database.cancel_job(row["id"]) is False

    def test_racing_workers_partition_the_queue(self, database, project):
        """Six real threads on one queue: every job claimed, none claimed twice."""
        queued = [
            database.insert("jobs", {
                "project_id": project["id"], "type": "generate", "status": "pending", "payload": {},
            })[0]["id"]
            for _ in range(24)
        ]
        claimed: list[str] = []
        ready = threading.Barrier(6)

        def drain() -> None:
            ready.wait()
            while True:
                job = database.claim_job()
                if job is None:
                    return
                claimed.append(str(job.id))

        run_threads(drain, count=6)

        assert sorted(claimed) == sorted(queued)

    def test_a_late_failure_cannot_undo_a_committed_result(self, database, project, knowledge_core):
        """A job reclaimed by the reaper runs twice; the loser must not erase the winner."""
        committed, job = run(database, project["id"], "generate", {
            "target_type": "quiz", "source_artifact_ids": [knowledge_core["id"]],
        })
        assert committed

        assert database.fail_job(job.id, "the slow worker finally gave up") == "completed"
        assert database.get_job(job.id)["status"] == "completed"

    def test_a_late_failure_cannot_undo_a_cancellation(self, database, project):
        row = database.insert("jobs", {
            "project_id": project["id"], "type": "generate", "status": "pending", "payload": {},
        })[0]
        database.claim_job(row["id"])
        assert database.cancel_job(row["id"]) is True

        assert database.fail_job(row["id"], "handler noticed later") == "cancelled"
        assert database.get_job(row["id"])["status"] == "cancelled"


class TestFlowConcurrency:
    def test_concurrent_completions_queue_the_next_step_once(self, database, project, knowledge_core):
        """Eight notifications for one finished step must produce one downstream job."""
        engine = FlowEngine(database)
        dispatched: list[str] = []

        engine.start(
            project["id"],
            [
                {"id": "s1", "type": "artifactNode", "data": {"artifact": {"id": knowledge_core["id"]}}},
                {"id": "g1", "type": "generator", "data": {"subType": "notes"}},
                {"id": "g2", "type": "generator", "data": {"subType": "quiz"}},
            ],
            [
                {"id": "e1", "source": "s1", "target": "g1"},
                {"id": "e2", "source": "g1", "target": "g2"},
            ],
            dispatch=dispatched.append,
        )
        run_id = engine.list_for_project(project["id"])[0]["id"]

        ready = threading.Barrier(8)
        failures: list[BaseException] = []

        def notify() -> None:
            try:
                ready.wait()
                engine.on_job_finished(run_id, "g1", artifact_id="notes-1", dispatch=dispatched.append)
            except BaseException as error:
                failures.append(error)

        run_threads(notify, count=8)

        assert not failures
        assert len(dispatched) == 2
        assert len(database.select("jobs", [("project_id", f"eq.{project['id']}")])) == 2
        assert engine.get(run_id)["node_states"]["g2"]["status"] == "running"

    def test_a_rolled_back_completion_publishes_nothing(
        self, database, project, knowledge_core, monkeypatch
    ):
        """The browser must never be shown a finished node the transaction threw away."""
        engine = FlowEngine(database)
        nodes, edges = notes_then_quiz(knowledge_core["id"])
        engine.start(project["id"], nodes, edges, dispatch=lambda _: None)
        run_id = engine.list_for_project(project["id"])[0]["id"]

        published = record_flow_events(monkeypatch)

        def refuse_to_schedule(*_args, **_kwargs):
            raise RuntimeError("nothing past this point reaches the commit")

        monkeypatch.setattr(FlowEngine, "_schedule", refuse_to_schedule)

        with pytest.raises(RuntimeError):
            engine.on_job_finished(run_id, "g1", artifact_id="notes-1")

        assert published == []
        assert engine.get(run_id)["node_states"]["g1"]["status"] == "running"

    def test_a_finished_run_publishes_its_events_in_order(
        self, database, project, knowledge_core, monkeypatch
    ):
        """Holding events back until the commit must not reorder or drop any of them."""
        published = record_flow_events(monkeypatch)
        engine = FlowEngine(database)
        nodes, edges = notes_then_quiz(knowledge_core["id"])

        engine.start(project["id"], nodes, edges, dispatch=lambda _: None)
        run_id = engine.list_for_project(project["id"])[0]["id"]
        engine.on_job_finished(run_id, "g1", artifact_id="notes-1")
        engine.on_job_finished(run_id, "g2", artifact_id="quiz-1")

        assert [
            (event_type, data.get("node_id"), data.get("status"))
            for event_type, data in published
        ] == [
            ("flow.started", None, None),
            ("flow.node", "g1", "running"),
            ("flow.node", "g1", "completed"),
            ("flow.node", "g2", "running"),
            ("flow.node", "g2", "completed"),
            ("flow.completed", None, None),
        ]
        assert published[-1][1] == {
            "flow_run_id": run_id, "completed": 2, "failed": 0, "skipped": 0,
        }


class RefusesTheFirstCommit:
    """
    Wraps a connection so its first `COMMIT` fails the way a full disk does.

    Only `execute` is interesting; everything else is the real connection, so
    `in_transaction` still reports what SQLite actually thinks.
    """

    def __init__(self, connection: sqlite3.Connection) -> None:
        self._connection = connection
        self._refuse = True

    def execute(self, sql: str, *parameters):
        if sql == "COMMIT" and self._refuse:
            self._refuse = False
            raise sqlite3.OperationalError("disk I/O error")
        return self._connection.execute(sql, *parameters)

    def __getattr__(self, name: str):
        return getattr(self._connection, name)


class TestTransactions:
    def test_a_failed_commit_leaves_the_connection_usable(self, database, project):
        """A commit that raises must still hand the thread back a usable connection."""
        flaky = RefusesTheFirstCommit(database._connection)
        database._local.connection = flaky

        with pytest.raises(sqlite3.OperationalError):
            database.insert("jobs", {
                "project_id": project["id"], "type": "generate", "status": "pending", "payload": {},
            })

        assert not flaky.in_transaction, "the failed commit stranded the connection"

        row = database.insert("jobs", {
            "project_id": project["id"], "type": "generate", "status": "pending", "payload": {},
        })[0]

        assert database.get_job(row["id"])["status"] == "pending"
        assert not flaky.in_transaction, "the later write joined a transaction that never ends"
